import Head from "next/head";

// Page Components
import RecentRewards from "@/components/rewards/RecentRewards";
import RewardHistory from "@/components/rewards/RewardHistory";
import RewardRelationship from "@/components/rewards/RewardRelationship";
import TotalRewards from "@/components/rewards/TotalRewards";

export default function Rewards() {
  return (
    <>
      <Head>
        <title>Rewards</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <div className="flex flex-wrap space-y-10">
        <div id="recent-rewards" className="w-full">
          <RecentRewards />
        </div>
        <div className="flex flex-col md:flex-row space-y-10 md:space-x-6 md:space-y-0 w-full">
          <div id="reward-history" className="w-full md:w-2/3">
            <RewardHistory />
          </div>
          <div id="total-rewards" className="w-full md:w-1/3">
            <TotalRewards />
          </div>
        </div>
        <div id="reward-relationship" className="w-full">
          <RewardRelationship />
        </div>
      </div>
    </>
  );
}
