import Head from "next/head";

// Page Components
import RecentTransfers from "@/components/stats/RecentTransfers";
import TotalTransfers from "@/components/stats/TotalTransfers";
import TransferHistory from "@/components/stats/TransferHistory";
import TransferRelationship from "@/components/stats/TransferRelationship";

export default function Stats() {
  return (
    <>
      <Head>
        <title>Stats</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <div className="flex flex-wrap space-y-10">
        <div id="recent-transfers" className="w-full">
          <RecentTransfers />
        </div>
        <div className="flex flex-col md:flex-row space-y-10 md:space-x-6 md:space-y-0 w-full">
          <div id="transfer-history" className="w-full md:w-2/3">
            <TransferHistory />
          </div>
          <div id="total-transfers" className="w-full md:w-1/3">
            <TotalTransfers />
          </div>
        </div>
        <div id="transfer-relationship" className="w-full">
          <TransferRelationship />
        </div>
      </div>
    </>
  );
}
