import Head from "next/head";

// Page Components
import Account from "@/components/overview/Account";
import BalanceDistribution from "@/components/overview/BalanceDistribution";
import BalanceHistory from "@/components/overview/BalanceHistory";
import BalanceStats from "@/components/overview/BalanceStats";
import BalancePieChart from "@/components/overview/BalancePieChart";
import Identity from "@/components/overview/Identity";

export default function Overview() {
  return (
    <>
      <Head>
        <title>Overview</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <div className="flex flex-wrap space-y-10">
        <div className="flex space-x-6 w-full">
          <div id="account" className="w-full md:w-2/3">
            <Account />
          </div>
          <div id="identity" className="w-full md:w-1/3">
            <Identity />
          </div>
        </div>
        <div id="balance-history" className="w-full">
          <BalanceHistory />
        </div>
        <div id="balance-pie-chart" className="w-full">
          <BalancePieChart />
        </div>
        <div className="flex flex-col md:flex-row space-y-10 md:space-x-6 md:space-y-0 w-full">
          <div id="balance-distribution" className="w-full md:w-2/3">
            <BalanceDistribution />
          </div>
          <div id="balance-stats" className="w-full md:w-1/3">
            <BalanceStats />
          </div>
        </div>
      </div>
    </>
  );
}
